name: 'Notify master failure'

on:
  workflow_run:
    branches: 
      - master
    workflows:
      - '**'
      - '!Markdown link check'
    types:
      - completed

jobs:
  slackNotify:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest
    steps:
      - name: Notify Brim HQ of failure on master
        uses: tiloio/slack-webhook-action@v1.1.2
        with:
          slack_web_hook_url: ${{ secrets.SLACK_WEBHOOK_BRIMLABS_TEST }}
          slack_json: |
            {
              "username": "github-actions",
              "text": "Workflow \"${{ github.event.workflow_run.name }}\" failed on master.\n${{ github.event.workflow_run.html_url }}"
            }  
